version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nowicki-naturalnie-frontend
    ports:
      - "3000:5173" # Map host port 3000 to container port 5173 (Vite default)
    volumes:
      # Mount the source code for hot-reloading
      # Use consistent volume definition
      - .:/app
      # Exclude node_modules from being overwritten by the host mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Add other environment variables if needed
    # Connect the service to the external optiq_prod network
    networks:
      - optiq_prod

# Define the external network
networks:
  optiq_prod:
    external: true

# Optional: Define volumes if needed for persistent data (not typical for frontend dev)
# volumes:
#   some-data:

